export const rows = [
  {
    id: 1,
    caseNo: "1222",
    caseStatus: "OPEN",
    createdDate: "02/05/2021 05:49:22 PM",
    subject: "Connection Issue",
  },
  {
    id: 2,
    caseNo: "1151",
    caseStatus: "Team Assigned",
    createdDate: "02/04/2021 02:33:22 PM",
    subject: "Connection Issue",
  },
  {
    id: 3,
    caseNo: "1149",
    caseStatus: "OPEN",
    createdDate: "02/01/2021 05:49:22 PM",
    subject: "Connection Issue",
  },
  {
    id: 4,
    caseNo: "1132",
    caseStatus: "OPEN",
    createdDate: "01/22/2021 05:49:22 PM",
    subject: "Issue with Payment",
  },
  {
    id: 5,
    caseNo: "1127",
    caseStatus: "OPEN",
    createdDate: "01/15/2021 05:49:22 PM",
    subject: "Issue with Payment",
  },
  {
    id: 6,
    caseNo: "1120",
    caseStatus: "OPEN",
    createdDate: "01/16/2021 05:49:22 PM",
    subject: "Connection Issue",
  },
  {
    id: 7,
    caseNo: "1114",
    caseStatus: "OPEN",
    createdDate: "02/05/2021 05:49:22 PM",
    subject: "Connection Issue",
  },
  {
    id: 8,
    caseNo: "1234",
    caseStatus: "Team Assigned",
    createdDate: "02/05/2021 05:49:22 PM",
    subject: "Issue with Payment",
  },
  {
    id: 9,
    caseNo: "1333",
    caseStatus: "Team Assigned",
    createdDate: "02/05/2021 05:49:22 PM",
    subject: "Issue with Payment",
  },
  {
    id: 10,
    caseNo: "1444",
    caseStatus: "OPEN",
    createdDate: "02/05/2021 05:49:22 PM",
    subject: "Connection Issue",
  },
  {
    id: 11,
    caseNo: "1454",
    caseStatus: "In Progress",
    createdDate: "02/05/2021 05:49:22 PM",
    subject: "Other Issue",
  },
];

export const columns = [
  {
    field: "caseNo",
    headerName: "Case Number",
    flex: 1,
    sortable: false,
    disableColumnMenu: true,
  },
  {
    field: "caseStatus",
    headerName: "Case Status",
    flex: 1,
    sortable: false,
    disableColumnMenu: true,
  },
  {
    field: "createdDate",
    headerName: "Created Date",
    flex: 1,
    filterable: false,
    sortable: false,
    disableColumnMenu: true,
  },
  {
    field: "subject",
    headerName: "Subject",
    flex: 1,
    sortable: false,
    disableColumnMenu: true,
  },
];
